[package]
name = "rustly"
version = "0.1.0"
edition = "2021"  

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustly"
path = "rustly/lib.rs"

[[bin]]
name = "rustly"
path = "rustly/main.rs"

[dependencies]
